version: '3'

services:
  app:
    image: chatgpt-to-api:1.0
    container_name: chatgpttoapi
    restart: unless-stopped
    ports:
      - '10080:10080'
    environment:
      SERVER_HOST: 0.0.0.0
      SERVER_PORT: 10080
      ADMIN_PASSWORD: sk-epoch-personal-gpt-key
      # Reverse Proxy - Available on accessToken
      API_REVERSE_PROXY: http://sj1.nonezero.top:8080/chatgpt/conversation
      # If the parameter API_REVERSE_PROXY is empty, the default request URL is https://chat.openai.com/backend-api/conversation, and the PUID is required.
      # You can get your PUID for Plus account from the following link: https://chat.openai.com/api/auth/session.
      PUID: user-GdnB7XWHPbuJYdnxrOt4yXVS
